language: node_js
node_js:
- "7"  # nodejs的版本
branches:
  only:
  - master  # 设置自动化部署的源码分支
env:
  global:  
    secure:
cache:
  apt: true
  directories:
    - node_modules

before_install:
- git config --global user.name "maoyiwei"
- git config --global user.email "jsmyw95@qq.com"
- npm install -g hexo-cli
- export TZ='Asia/Shanghai'
before_script:

# 安装依赖组件
install:
- npm install
- sudo apt install pandoc -y
# 执行的命令
script:
- hexo clean
- hexo generate
# 执行的成功后执行 
after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
# 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的
- git push --quiet --force https://$REPO_TOKEN@$REPO_REF
  master
