# Icon
favicon: /favicon.ico
## Keywords for SEO
keywords: 毛怡伟,毛线
# Header
page_background: /assets/fantasy.jpg
page_menu_button: dark
post_background: /assets/cats.jpg
post_menu_button: light
title_plancehold: 随笔
author:
  head: /assets/woolen.jpg
  signature: 做有情怀的程序员
navication:
  - name: Github
    link: https://github.com
  - name: V2EX
    link: https://www.v2ex.com/
# content
content_width: 800
# Footer
## Social icon list: [facebook, twitter, weibo, wechat, github, stackoverflow, linkin, email, segmentfault, flickr, zhihu, disqus, douban, bilibili]
social:
  - name: Github
    icon: github
    link: https://github.com/sanmaopep

# Duoshuo
duoshuo:
  enable: true
  siteName: ueibo
# Copyright
copyright:
  record: false
  hexo: true
  laughing: true